### ISSUE TITLE
Compatibility issue with linter-phpcs

### ISSUE THREAD

**Issue by burhandodhy** [jcartledge/atom-phpcbf#6]
When ever  i run PHPCBFReformat function the standards warning given by linter-phpcs are gone.. Kindly solve this problem thanks

**Comment by jcartledge** [comment]
Hi,

I'm not sure I understand the issue.

PHPCBF corrects the problems identified by PHPCS. After running reformat you should not see any linting warnings because the problems causing them have been fixed.

If there are any problems PHPCBF doesn't fix then the linting warnings/errors remain visible - at least, that's what happens when I use it.

Can you please give me more information so I can reproduce the problem:
- sample code I can use to reproduce this
- what coding standard you are using

Thanks.

**Comment by jcartledge** [comment]
Please reopen with info requested if this is still an issue.
